### ISSUE TITLE
Won't compile in x86_64 GNU/Linux

### ISSUE THREAD

**Issue by schnorr** [soctrace-inria/prv2pjdump#1]
I just cloned the repository, typed `make` and got an error. Then, I entered in the `linux_x64` directory, typed the following command to also reproduce the error:

``` bash
$ g++ -O3 -Wall -c -fmessage-length=0  -std=c++11 -std=c++0x -MMD -MP -MF"src/prv2pjdump.d" -MT"src/prv2pjdump.o" -o "src/prv2pjdump.o" "../src/prv2pjdump.cpp"
../src/prv2pjdump.cpp: In function ‘bool exist(std::__cxx11::string)’:
../src/prv2pjdump.cpp:128:9: error: cannot convert ‘std::ifstream {aka std::basic_ifstream<char>}’ to ‘bool’ in return
  return ifile;
```

Do you have any suggestion to fix it? Thanks in advance.

**Comment by ycorre** [comment]
OK, I changed the returned value to so that a boolean is explicitly returned.
